//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID_country { get; set; }
        public string Name { get; set; }
        public string Сapital { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Heritage { get; set; }
        public string Сontinent { get; set; }
    }
}
