//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disciplin()
        {
            this.Exams = new HashSet<Exams>();
            this.Zaivka1 = new HashSet<Zaivka1>();
        }
    
        public int Kod { get; set; }
        public Nullable<int> Volume { get; set; }
        public string Name { get; set; }
        public string cipher { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        public virtual Kafedra Kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams> Exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaivka1> Zaivka1 { get; set; }
    }
}
