//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Exams = new HashSet<Exams>();
        }
    
        public int ID_employee { get; set; }
        public string cipher { get; set; }
        public string Surname { get; set; }
        public string Post { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> ID_prepod { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        public virtual Kafedra Kafedra { get; set; }
        public virtual Zav_Kafedra Zav_Kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams> Exams { get; set; }
        public virtual Ingener Ingener { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
