//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        public int ID_exam { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Kod { get; set; }
        public Nullable<int> Id_stud { get; set; }
        public Nullable<int> Tab_number { get; set; }
        public string Auditor { get; set; }
        public Nullable<int> Atmetk { get; set; }
        public Nullable<bool> Visiable { get; set; }
    
        public virtual disciplin disciplin { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
