//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gimnazia
    {
        public int ID { get; set; }
        public string SURNAME { get; set; }
        public string Predmet { get; set; }
        public string SCHOOL { get; set; }
        public Nullable<double> POINTS { get; set; }
    }
}
