//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AkademiaEntities : DbContext
    {
        public AkademiaEntities()
            : base("name=AkademiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Animal_Popelyuk> Animal_Popelyuk { get; set; }
        public virtual DbSet<Control_Popelyuk> Control_Popelyuk { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Country_Popelyuk> Country_Popelyuk { get; set; }
        public virtual DbSet<disciplin> disciplin { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Exams> Exams { get; set; }
        public virtual DbSet<Facultet> Facultet { get; set; }
        public virtual DbSet<Flowers_Popelyuk> Flowers_Popelyuk { get; set; }
        public virtual DbSet<Ingener> Ingener { get; set; }
        public virtual DbSet<Kafedra> Kafedra { get; set; }
        public virtual DbSet<Specialnost> Specialnost { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Studik> Studik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Zaivka1> Zaivka1 { get; set; }
        public virtual DbSet<Zav_Kafedra> Zav_Kafedra { get; set; }
        public virtual DbSet<Gimnazia> Gimnazia { get; set; }
    }
}
