//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaStudPractics.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaivka1
    {
        public int ID { get; set; }
        public Nullable<int> Kod { get; set; }
        public string Number { get; set; }
    
        public virtual disciplin disciplin { get; set; }
        public virtual Specialnost Specialnost { get; set; }
    }
}
